---
# GitHub Actions workflow for commits pushed to the Macana repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java17-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v4
        with:
          repository: 'MyWorldLLC/Obsidian'
          ref: '037eb4d'
      - run: |
            cd Obsidian
            ./gradlew :Obsidian:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf Obsidian
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - run: ./gradlew build --console=plain --stacktrace

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-13
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/checkout@v4
        with:
          repository: 'MyWorldLLC/Obsidian'
          ref: '037eb4d'
      - run: |
            cd Obsidian
            ./gradlew :Obsidian:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf Obsidian
      - uses: actions/checkout@v4
      - run: ./gradlew build --console=plain --stacktrace

  Java21-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v4
        with:
          repository: 'MyWorldLLC/Obsidian'
          ref: '037eb4d'
      - run: |
            cd Obsidian
            ./gradlew :Obsidian:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf Obsidian
        shell: bash
      - uses: actions/checkout@v4
      - run: ./gradlew build --console=plain --stacktrace
        shell: bash
