---
# GitHub Actions workflow for commits pushed to the Macana repo - all branches

name: CI at GitHub
on: [push]

jobs:
  Java17-Linux:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: |
            git clone https://github.com/MyWorldLLC/Obsidian.git
            cd Obsidian
            git checkout -b snapshot 037eb4d
            ./gradlew :Obsidian:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf Obsidian
      - run: |
            git clone https://github.com/stephengold/sport.git
            cd sport
            git checkout -b snapshot 30040e
            ./gradlew :lib:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf sport
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - run: ./gradlew build --console=plain --no-daemon --stacktrace

  Java17-MacOS:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: macOS-14
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: |
            git clone https://github.com/MyWorldLLC/Obsidian.git
            cd Obsidian
            git checkout -b snapshot 037eb4d
            ./gradlew :Obsidian:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf Obsidian
      - run: |
            git clone https://github.com/stephengold/sport.git
            cd sport
            git checkout -b snapshot 30040e
            ./gradlew :lib:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf sport
      - uses: actions/checkout@v4
      - run: ./gradlew build --console=plain --no-daemon --stacktrace

  Java17-Windows:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: windows-2022
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - run: |
            git clone https://github.com/MyWorldLLC/Obsidian.git
            cd Obsidian
            git checkout -b snapshot 037eb4d
            ./gradlew :Obsidian:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf Obsidian
        shell: bash
      - run: |
            git clone https://github.com/stephengold/sport.git
            cd sport
            git checkout -b snapshot 30040e
            ./gradlew :lib:publishToMavenLocal --console=plain --stacktrace
            cd ..
            rm -rf sport
        shell: bash
      - uses: actions/checkout@v4
      - run: ./gradlew build --console=plain --no-daemon --stacktrace
        shell: bash
